### ISSUE TITLE
A row with extra comma is not repaired correctly

### ISSUE THREAD

**Issue by weiyixia** [weiyixia/CSV-file-repair#4]
The correct row is: 
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The broken row is:
333,743,FL,CLAY C,OUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The fixed row is:
333,743 743 743 743,OUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3,

**Comment by weiyixia** [comment]
A simplified test case:
The correct row is: 
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The broken row is:
333,743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The fixed row is:
333,743 743,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3,

**Comment by weiyixia** [comment]
A simplified test case:
The correct row is: 
333743,FL,CLAY COUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The broken row is:
333743,FL,CLAY C,OUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3

The fixed row is:
333743,FL,CLAY C OUNTY,0,79520.76,0,0,79520.76,86854.48,0,0,0,0,30.063236,-81.707703,Residential,Wood,3,

**Comment by lnyemba** [comment]
Good deal. It seems we have achieved correctness
